### ISSUE TITLE
sendBuddyMessage 无法发送消息

### ISSUE THREAD

**Issue by gao03** [eyeKill/pyQQRobot#1]
之前sendMessage可以给好友发消息的，现在不可以了，提示KeyError。
另外，sendGroupMessage我试了几次也没能成功发送消息。

**Comment by egnchen** [comment]
新版里加了send_group_message的功能，之前版本的sendGroupMessage是废柴。
可能的错误问题可能我要留着解决，麻烦事多着。
注意新版里面的命名依照pep8规范，详见README和example.py
