### ISSUE TITLE
retcode 1202.

### ISSUE THREAD

**Issue by WuTianming** [eyeKill/pyQQRobot#3]
出现retcode 1202，log显示发送成功，但是接收者未收到信息。

而且，这个号用webQQ也无法发送消息了，请问有人知道为啥吗？

**Comment by egnchen** [comment]
这个问题确实头疼 webqq本身也无视1202的，
但我自己测试的时候是没有问题。

**Comment by WuTianming** [comment]
@eyeKill 还有个问题，我现在测试程序是“一旦收到好友信息就回复一条固定的消息”，为什么在运行了半个小时之后这个帐号能收到信息，console里发送也显示成功，但是别人收不到；webQQ登录之后也是，发出去收不到。这是疼讯的问题还是程序的问题？

**Comment by egnchen** [comment]
？既然WebQQ也发不出去可能是tx的问题？ 我建议你换个号试试看。

**Comment by WuTianming** [comment]
@eyeKill 好像是tx问题... 换了个号一切正常。可能是tx检测到spam了
