### ISSUE TITLE
What is in dev/ ?

### ISSUE THREAD

**Issue by WuTianming** [eyeKill/pyQQRobot#4]
I just wonder what is the JS file in the dir dev/. We just need the python codes from src/, right?

**Comment by egnchen** [comment]
That's right, ignore the js file.
The js file is dumped from `w.qq.com`. Consider it as the WebQQ html application itself.
The module `mq.model.memberlist` in that js file contains the WebQQ protocol, which is the main reference of pyQQRobot.

**Comment by WuTianming** [comment]
哦懂了，这是你从WebQQ上面扒下来的原版web程序对吧，里面有接口信息，然后你是照着这个写的代码。可敬的coder！
