### ISSUE TITLE
How to send msgs to a group

### ISSUE THREAD

**Issue by WuTianming** [eyeKill/pyQQRobot#5]
你没告诉我们怎么处理群和讨论组啊，难道让我自己翻代码？

（好像也不是不可以，但是你至少加个API手册吧）

**Comment by egnchen** [comment]
in QQHandler(or QQClient):
- send message to a buddy `self.send_buddy_message(uin, content)`
- send message to a group `self.send_group_message(gid, content)`
- send message to a discuss group `print("lol I haven't written that sorry")`

**Comment by WuTianming** [comment]
@eyeKill 我刚刚翻的源码已经知道了（（抱歉没有及时看到
