### ISSUE TITLE
So slow after update

### ISSUE THREAD

**Issue by WuTianming** [eyeKill/pyQQRobot#8]
更新之后特别慢，从veri文件里读入完Username之后就卡很长时间才登录，登录之后获取消息延迟特别大，如果直接扫码登录的话也是特别慢。是代码问题吗？

**Comment by egnchen** [comment]
我自己测试没有问题。
你是不是大量使用了`get_group_info()`？
这个方法首次获取某个群的信息会进行网络请求，而且数据量很大（上百人的群会有300k+），并且是同步的，所以会很慢，这是可能的原因。
获取同一个群第二次就不会有网络请求了。但是不会保存到磁盘，重新打开以后还是会。

**Comment by WuTianming** [comment]
完全没有啊，是不是我帐号问题？
我是仅仅执行一个a.login(get啥啥的=False)，然后应该有三行提示消息，这三行字好长时间才出来
可能是我的帐号被封了吧... 确实webqq容易被封

**Comment by egnchen** [comment]
那我确实是不知道，问题没办法重现我也就没办法解决。。。
