### ISSUE TITLE
现在默认就是gevent，怎么使用原来的http？

### ISSUE THREAD

**Issue by WuTianming** [eyeKill/pyQQRobot#9]
RT.

**Comment by WuTianming** [comment]
Fixed by reading the source code.

**Comment by WuTianming** [comment]
Traceback (most recent call last):
  File "./QQgetMsg.py", line 26, in <module>
    a.load_veri(sys.argv[1])
  File "/home/wtm/Working/QQRobot/qqrobot.py", line 258, in load_veri
    self.http_client.set_cookie(name, value, domain)
  File "/home/wtm/Working/QQRobot/qqhttp.py", line 55, in set_cookie
    raise NotImplementedError()
NotImplementedError
^WTF?

**Comment by WuTianming** [comment]
难道没写完 是不是因为还在测试？

**Comment by egnchen** [comment]
You must have imported the wrong class. Use:

``` python
from qqhttp import mHTTPClient_urllib
```

instead of:

``` python
from qqhttp import mHTTPClient
```

then

``` python
a = QQClient(HTTPClient=mHTTPClient_urllib)
```

`mHTTPClient` is the base class, or framework, only contains abstract methods. `mHTTPClient_urllib` is its implementation.

**Comment by WuTianming** [comment]
@eyeKill 我知道了 我用的是`QQClient(HTTPClient=mHTTPClient)`，就这里出问题了，谢谢

**Comment by egnchen** [comment]
On the other hand, I'm going to abandon `qqhttp` and use `requests` library instead.
I gotta say, it's like hell to maintain a http library for a small project.
